### ISSUE TITLE
Would be nice if it synced like a week in advance instead of day per day

### ISSUE THREAD

**Issue by kenjibailly** [saberzero1/habitica-google-calendar#1]
At the moment it syncs each day of that day only. 
Would be nice if the script would sync a week in advance so you can see what your to do's are in habitica for the upcoming week.

Thanks for the awesome script btw!

**Comment by saberzero1** [comment]
Change the below snippet:

https://github.com/saberzero1/habitica-google-calendar/blob/8276821a9ff5d831d5d78518379032d1ff7f36e3/habitica-google-calendar.gs#L17-L23

Change to the following lines:

```Javascript
 function scheduleToDos() { 
   var now = new Date(); 
    
   // Get current date 
   var today = new Date(); 
   var endOfWeek = new Date(); 

   var daysAhead = 7;  // Number of days to sync ahead
   now.setDate(now.getDate() + daysAhead);
   today.setDate(today.getDate() + daysAhead);
   endOfWeek.setDate(endOfWeek.getDate() + daysAhead);

   var events = CalendarApp.getCalendarsByName(calendarMame)[0].getEventsForDay(now); 
```

It will start syncing seven days ahead; thus, you will be missing the next seven days.
To fix that, manually run the program seven times with `var daysAhead=x;` where `x = 0,1,2,3,4,5,6`
Afterwards, the program should sync seven days ahead.
Do note that using the program in this way will not sync tasks added in less than a week from now.
It is therefore only useful for tasks that are planned a week ahead or keeping a regular schedule.
Hope this helps.

**Comment by kenjibailly** [comment]
I see, I didn't know that was the restriction.
Is there no way to get info through the api to check wether the todo has already been posted or not and check that every day for the next 7 days?
I'm not familiar with the API of habitica, let me know.

Another question you might be able to answer. Is it possible to create a 2 way sync? 
Say you click done on habitica on a todo that the even goes away in Google Calendar?

Let me know, I can program a bit myself, I'd def would wanna help out or check deeper how to do it if it's possible ofc.

**Comment by saberzero1** [comment]
https://github.com/saberzero1/habitica-google-calendar/blob/main/habitica-google-calendar-v2.gs

I have done some work on adapting this repo: https://github.com/davicedraz/habitica-google-calendar/blob/master/index.gs
I think it addresses both of your concerns.
The new file will insert events from a given Google Calendar calendar for the next seven days as dailies into your Habitica.
The daily will have a start date of the due date in Google calendar.
When a daily is checked off in Habitica, it is fetched by the script, and the respective Google calendar entry is removed.
I suggest setting the script on a 5-minute trigger, as the script only updates when it is run,

There are currently two problems with this implementation:
 - If you have duplicate titles in Google calendar, it will remove all of them when one of the dailies with that title is done.
 - You cannot use checklist items like you could with my old implementation.

I'll have to look into both the Habitica API and Google Calendar API to fix the above issues.
I'll address these issues later, but first, please check out if this implementation is getting close to what you had in mind.

**Comment by saberzero1** [comment]
I fixed the duplicate title problem.

**Comment by kenjibailly** [comment]
I'm getting an error on this line:
`sortArray.push({date: sorting.data[i].startDate, time: sorting.data[i].notes.substring(15, sorting.data[i].notes.length-1), id: sorting.data[i]._id});`

TypeError: Cannot read property 'substring' of null
syncToHabbitica	@ Code.gs:111

**Comment by saberzero1** [comment]
I have just pushed a new version.
This version allows you to once again have subtasks as description lines.
Please let me know if this version still has the above issue.

**Comment by kenjibailly** [comment]
I'm getting another error:

TypeError: Cannot read property 'substring' of null
syncToHabbitica	@ Code.gs:142

`sortArray.push({date: sorting.data[i].startDate, time: sorting.data[i].notes.substring(15, sorting.data[i].notes.length-1), id: sorting.data[i]._id});`

**Comment by saberzero1** [comment]
I have added some sanity checks, please check if this fixes your issue.

**Comment by kenjibailly** [comment]
So I just read up, it's working. But they don't come in as to do's, which seems to be intentionally.
Unfortunately it's kinda unhandy as they are only shown under "not due" so to see them you have to click that button. 
In to do's rather they are all shown with their according date. I'm just wondering, is it not possible.

Also thank you for all the changes, it's working :)

**Comment by saberzero1** [comment]
![image](https://user-images.githubusercontent.com/8161064/149221363-a9a3fc4b-07a1-487b-ba5b-2c9d376687e2.png)
If you click the "all" button, it will show all of them.
On mobile, uncheck the "Set Dailies default to 'due' tab"
![image](https://user-images.githubusercontent.com/8161064/149222410-327c71bc-88f7-44bf-8f22-261d68b0ce73.png)
I hope this solves your problem.

**Comment by saberzero1** [comment]
I noticed that my dailies were not syncing their respective subtasks. The most recent version fixes the issue, as mentioned earlier. Therefore, I will be closing this issue. Feel free to re-open it if needed.
